### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by HydrofinLoewenherz** [scrayosnet/xenos#1]
# Roadmap

The following features are planned. The order is approximately the order in which we will implement them.

- [x] Implement the GRPC Health Checking Protocol (https://github.com/grpc/grpc/blob/master/doc/health-checking.md)
- [ ] Integrate Prometheus for avg response time, status codes, cache hits/misses, Mojang response time (with quartiles)
- [ ] Update proto documentation
- [ ] Update code documentation
- [ ] Update README to include usage documentation
- [ ] Provide REST api next to GRPC
- [ ] Add helm-chart and other deployments
- [ ] Add different cache types (e.g. redis, in-memory, ...)
- [ ] Cache Mojang session server

**Comment by scrayos** [comment]
This issue was split into separate issues.
